apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vmmanagers-tls
spec:
  secretName: vmmanagers-tls
  dnsNames:
    - "vmmanagers.com"
    - "api.vmmanagers.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
